### ISSUE TITLE
Ability to handle data [0, 0, 0, 0]

### ISSUE THREAD

**Issue by adin-ttc** [greghub/funnel-graph-js#11]
Expect: a thin line as shown in last 3 columns of data = [100, 0, 0, 0]
Actual: no line at all

Expect: percentages to be empty
Actual: NaN%

**Comment by kelvinmaues** [comment]
@greghub I think you can close this issue now.

**Comment by kelvinmaues** [comment]
Do not forget to build the project to NPM, pls. Thanks!

**Comment by greghub** [comment]
@kelvinmaues Thank you! your updates have been published in version `1.4.0`
