### ISSUE TITLE
[Feature Request] Allow decimals for values.

### ISSUE THREAD

**Issue by popovicieduard** [greghub/funnel-graph-js#12]
I am using this package with nuxt and I can't find a way for showing decimals for values in the graph, for example if I want to show some percentge for a value: (5.72), it is rounded to 6 and  formatted to 0 decimals, did some digging and found that number.js from src/js/number is responsible for formatting the numbers. It would be nice to be able to pass decimal option to values.

for example: 
`                <vue-funnel-graph
                    :values="values"
                ></vue-funnel-graph>`

`data(){
return {
values: [
[this.statistics.spend],[this.statistics.clicks],[this.statistics.leads],[(this.statistics.leads / this.statistics.clicks * 100), { decimals: 2 }]
]
}
}`

Thanks.

**Comment by greghub** [comment]
@popovicieduard Thank you for raising the issue! Fixed in version `1.4.0`
