### ISSUE TITLE
Labels are printed on the graph when they are a certain length

### ISSUE THREAD

**Issue by C4rter** [greghub/funnel-graph-js#13]
When a label is a bit longer, it's printed onto the funnel graph.
Can there be a line break instead?

![Screenshot_2019-10-06 SVG Funnel](https://user-images.githubusercontent.com/738782/66267475-62320e80-e831-11e9-8407-1a0f3be59ef5.png)

**Comment by greghub** [comment]
@C4rter sorry for the late reply. A lot of visual changes in this library are intended to be done using CSS. So I would suggest setting a `max-width` on the `.label__title` class. That will break the line if the title is longer than the max width
