### ISSUE TITLE
Unable to use dynamic data

### ISSUE THREAD

**Issue by emilrowland** [greghub/funnel-graph-js#15]
When I call the `graph.updateData({data})` function it redraws the funnel but don't update the counter labels and percentage . If i call it twice it updates the count label as well but the percentage is not being updates. if I call `graph.data` I can still see the init data there and not the new data set by `graph.updateData()`.

**Comment by greghub** [comment]
@emilrowland thank you for opening the issue! It is now fixed in version `1.4.1`
