### ISSUE TITLE
[Feature Request] Allow display of raw values instead of %

### ISSUE THREAD

**Issue by lordplagus02** [greghub/funnel-graph-js#3]
It would be very useful if the chart could display the "nested values" used for sub-labels in their raw form. That would allow for things like displaying a count of data rows that make up the segment, per segment, or prefixing your values with a currency symbol.
Currently you can only use sub-labels to display calculated percentages. 

TL;DR: **I want to just display some calculated raw values/data _about_ each funnel stage with sub-labels on segment/stage hover**

**Comment by greghub** [comment]
Hi @lordplagus02 , thank you for your interest in Funnel Graph JS!
I've added a `subLabelValue` option that can be set to `raw` to display raw value on the sub-labels.
Funnel Graph gives a lot of controls over how it is displayed by using CSS. If you want to add a prefix to the label you can use the `:before` pseudo class and specify the prefix as a value for the `content` property. Same can be used for postfix.

<img src="https://i.imgur.com/we5uERV.png">
