### ISSUE TITLE
Resize funnel on window resize

### ISSUE THREAD

**Issue by maitsa** [greghub/funnel-graph-js#4]
There's a way to redraw the funnel svg on window resize?

**Comment by greghub** [comment]
Hi @maitsa ,
do you need to update the funnel size on window resize? You can use `updateHeight` and `updateWidth` methods to do that. If that doesn't solve your issue, please let me know

**Comment by maitsa** [comment]
I tried exactly that before post this issue.
Anyway I found a way to get it works. I used the parent of the funnel container to update the width.


    var funnelContainer = $('.funnel'),
    var graph = new FunnelGraph({
        container: '.funnel',
        gradientDirection: 'horizontal',
        data: funnelGraphData,
        displayPercent: false,
        direction: 'horizontal',
        width: funnelContainer.parent().width(),
        height: 150,
    });

    $(window).on('resize', function () {  graph.update({ width: funnelContainer.parent().width() }); });

**Comment by greghub** [comment]
Great, this is correct, I'm closing the issue, but I will add an option for that in the nearest future
