### ISSUE TITLE
[Bug] Zeroes in values array break chart render

### ISSUE THREAD

**Issue by lordplagus02** [greghub/funnel-graph-js#6]
For the following data object, I get an incredibly weird chart:
```
labels: Array(4)
  0: "One"
  1: "Two"
  2: "Three"
  3: "Four And A Half"
subLabels: Array(4)
  0: "Beauty"
  1: "Health"
  2: "Fashion"
  3: "Other"
values: Array(4)
  0: (4) [30000, 10000, 5000, 5000]
  1: (4) [5000, 5000, 10000, 15000]
  2: (4) [0, 0, 0, 0]
  3: (4) [0, 0, 0, 0]
```
See screenshot
![image](https://user-images.githubusercontent.com/11164562/57809547-f2c66000-7765-11e9-989c-0c353b2ff8e6.png)

JSFiddle: https://jsfiddle.net/3mb6vkr5/

**Comment by lordplagus02** [comment]
I get errors in console with this sort of data set, example:
![image](https://user-images.githubusercontent.com/11164562/57848918-512d2600-77da-11e9-8952-42810b57d5ca.png)

**Comment by lordplagus02** [comment]
I've localized the issue. If there are **only 0s in the last row of the data set** it breaks the chart.

**Comment by lordplagus02** [comment]
@greghub Are you able to take a look at this? 🙏

**Comment by greghub** [comment]
@lordplagus02 Hi, thank you for raising the issue, fixed it in version `1.3.8`, please check

**Comment by lordplagus02** [comment]
It looks better, but please note that I still get errors in the browser console if any of the rows are 0s, and the chart still doesn't look quite right if there are zeroes preceding non-zeroes.

**Comment by greghub** [comment]
Hi @lordplagus02 , cannot reproduce the problem on Chrome, Firefox, Opera and IE11. Could you please describe what sort of errors do you see and how the chart does not look right?
